### ISSUE TITLE
Nedostatky předběžné verze [2024-12-22]

### ISSUE THREAD

**Issue by Polda18** [POL0423/TAMZ#2]
Dokončené části základní kostry:
- Hlavní menu se třemi základními stránkami (prostory bez obsahu)
  - Domovská stránka
  - Dnešní předpověď
  - Týdenní předpověď
- Připravená stránka s mapou, nastavením a stránka "About"
  - Jedná se o prostory, bez vlastního obsahu
- Ikona aplikace ve spouštěči a notifikacích
- Ikony v menu

Nedokončené části základní kostry:
- nelze se přepnout do nastavení
- nefunguje položka "About" v menu tří teček
- nejsou připraveny fake data k připravení vizuální prezentace dat
- Mapa není využita

Nebyl jsem schopen ve vyhledávači najít způsob, jak se z menu tří teček dostat na stránku s nastavením, stejně tak jsem nebyl schopen najít způsob, jak se dostat ze stejného menu na stránku "About". Pravděpodobně musím vytvořit nové aktivity, ale na internetu se zdá, že chybí postup. Z důvodu docházejícího času (a nutnosti spánku), jsem musel projekt odevzdat v nedopracované fázi základní kostry, hluboce jsem podcenil komplexitu celého tématu a vyhradil si příliš málo času na řešení. Za to se omlouvám.

**Comment by MKrumnikl** [comment]
Stačilo přidat callback metodu na události menu, konkrétně onOptionsItemSelected a poté pomocí navigation controlleru přepnout daný fragment.

    public boolean onOptionsItemSelected(@NonNull MenuItem item) {
        if (item.getItemId() == R.id.action_settings) {
            navController.navigate(R.id.nav_settings);
        }
        if (item.getItemId() == R.id.action_about) {
            navController.navigate(R.id.nav_about);
        }

        Log.d("MENU", "Menu selected " + item.getItemId());
        return super.onOptionsItemSelected(item);
    }

**Comment by Polda18** [comment]
Díky, kód jsem přidal do `MainActivity.java`, do třídy `MainActivity`, otestoval, a funguje to! Všechno tím pádem je připraveno na doplnění ostatních částí a dokončení celého projektu.
